=== osc-em/OSCEM_Schemas/Processing/processing.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schemas.com/processing/processing",
    "title": "import_movies",
    "description": "JSON Schema for electron microscopy processing",
    "type": "object",
    "properties": {
        "Import_movies": {
            "$ref": "import_movies.json"
        },
        "Movie_alignment": {
            "$ref": "movie_alignment.json"
        },
        "Movie_maxshift": {
            "$ref": "movie_maxshift.json"
        },
        "CTF_estimation": {
            "$ref": "CTF_estimation.json"
        },
        "Particle_picking": {
            "$ref": "particle_picking.json"
        },
        "Classes_2D": {
            "$ref": "classes2D.json"
        },
        "Initial_volume": {
            "$ref": "initial_volume.json"
        },
        "Classes_3D": {
            "$ref": "classes3D.json"
        }
    },
    "additionalProperties": false
}

=== osc-em/OSCEM_Schemas/Processing/processing_valid_example.json
{
    "Import_movies": {
        "Microscope_voltage_(kV)": 300.0,
        "Spherical_aberration_(mm)": 2.7,
        "Amplitud_contrast": 0.1,
        "Pixel_size_(Å/px)": 0.495,
        "Gain_image": "gain.jpg",
        "Number_movies": 30,
        "Frames_per_movie": 50,
        "Frames_size_(pixels)": "3710 x 3838"
    },
    "Movie_alignment": {
        "Method": "XmippProtFlexAlign",
        "Binning_factor": 1.0,
        "Maximum_resolution_(Å)": 30.0,
        "Frames_aligned": {
            "Frame0": 1,
            "FrameN": 30
        },
        "Output_avg_shift_(Å)": 11.9,
        "Output_max_shift_(Å)": 33.8
    },
    "Movie_maxshift": {
        "Discarded_movies": 7,
        "Max_frame_shift_(Å)": 5.0,
        "Max_movie_shift_(Å)": 20.0,
        "Rejection_type": "By frame or movie",
        "Output_avg_shift_(Å)": 11.9,
        "Output_max_shift_(Å)": 29.7,
        "Shift_histogram": "shift_hist.jpg"
    },
    "CTF_estimation": {
        "Defocus_(Å)": {
            "Output_max_defocus": 11850.6,
            "Output_min_defocus": 1539.1,
            "Output_avg_defocus": 2618.7,
            "Defocus_histogram": "defocus_hist.jpg",
            "Micrograph_examples": "Micro_examples/micro_defocus.jpg"
        },
        "Resolution_(Å)": {
            "Output_max_resolution": 3.6,
            "Output_min_resolution": 2.2,
            "Output_avg_resolution": 2.9,
            "Resolution_histogram": "resolution_hist.jpg"
        },
        "Astigmatism": {
            "Astigmatism_histogram": "astigmatism_hist.jpg"
        }
    },
    "Particle_picking": {
        "Number_particles": 3158,
        "Particles_per_micrograph": 137.3,
        "Particles_histogram": "particles_hist.jpg",
        "Micrograph_examples": "Micro_examples/micro_particles.jpg"
    },
    "Classes_2D": {
        "Number_classes_2D": 48,
        "Particles_per_class": [
            846,
            546,
            193,
            158,
            117,
            113,
            96,
            86,
            69,
            64,
            61,
            51,
            47,
            46,
            39,
            34,
            34,
            34,
            33,
            31,
            29,
            28,
            25,
            25,
            25,
            23,
            22,
            21,
            21,
            20,
            20,
            20,
            19,
            19,
            18,
            17,
            17,
            14,
            13,
            13,
            12,
            11,
            7,
            7,
            6,
            4,
            2,
            2
        ],
        "Images_classes_2D": "classes_2D.jpg"
    },
    "Initial_volume": {
        "Orthogonal_slices": {
            "Orthogonal_slices_X": "Initial_volume/orthogonal_slices/orthogonal_slices_X.jpg",
            "Orthogonal_slices_Y": "Initial_volume/orthogonal_slices/orthogonal_slices_Y.jpg",
            "Orthogonal_slices_Z": "Initial_volume/orthogonal_slices/orthogonal_slices_Z.jpg"
        },
        "Isosurface_images": {
            "Front_view": "Initial_volume/isosurface_images/front_view.jpg",
            "Side_view": "Initial_volume/isosurface_images/side_view.jpg",
            "Top_view": "Initial_volume/isosurface_images/top_view.jpg"
        }
    },
    "Classes_3D": {
        "Number_classes_3D": 2,
        "Particles_per_class": [
            2509,
            649
        ],
        "Images_classes_3D": "Classes_3D/classes_3D.jpg",
        "Volumes": {
            "Volume_1": {
                "Orthogonal_slices": {
                    "Orthogonal_slices_X": "Classes_3D/orthogonal_slices_volume1/orthogonal_slices_X.jpg",
                    "Orthogonal_slices_Y": "Classes_3D/orthogonal_slices_volume1/orthogonal_slices_Y.jpg",
                    "Orthogonal_slices_Z": "Classes_3D/orthogonal_slices_volume1/orthogonal_slices_Z.jpg"
                },
                "Isosurface_images": {
                    "Front_view": "Classes_3D/isosurface_images_volume1/front_view.jpg",
                    "Side_view": "Classes_3D/isosurface_images_volume1/side_view.jpg",
                    "Top_view": "Classes_3D/isosurface_images_volume1/top_view.jpg"
                }
            },
            "Volume_2": {
                "Orthogonal_slices": {
                    "Orthogonal_slices_X": "Classes_3D/orthogonal_slices_volume2/orthogonal_slices_X.jpg",
                    "Orthogonal_slices_Y": "Classes_3D/orthogonal_slices_volume2/orthogonal_slices_Y.jpg",
                    "Orthogonal_slices_Z": "Classes_3D/orthogonal_slices_volume2/orthogonal_slices_Z.jpg"
                },
                "Isosurface_images": {
                    "Front_view": "Classes_3D/isosurface_images_volume2/front_view.jpg",
                    "Side_view": "Classes_3D/isosurface_images_volume2/side_view.jpg",
                    "Top_view": "Classes_3D/isosurface_images_volume2/top_view.jpg"
                }
            }
        }
    }
}
